exec-once = waybar
exec-once = swaybg -i ~/nixos-dotfiles/config/swaybg/wallpapers/tokyo-night-1.jpg
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=mango
exec-once = systemctl --user restart xdg-desktop-portal-wlr xdg-desktop-portal

exec-once = sh -lc 'wl-paste --type text --watch cliphist store'
